version: '3'

services:

  www:
    image: 'tmvdl/projects:counter'
    restart: 'always'
    build: './src/www'
    volumes:
      - './src/www:/app'
    ports:
      - '80:3000'

  docker-push:
    image: 'docker-push'
    build: './src'

  github-release:
    image: 'github-release'
    build: './src'
