version: '3'

services:

  www:
    restart: 'always'
    build: './src/www'
    volumes:
      - './src/www:/app'
    ports:
      - '80:3000'

  app:
    build: './src/app'
    volumes:
      - './src/app:/app'
      - './src/www/src:/app/src'
    ports:
      - '3000:3000'
