version: '3'

services:
  app:
    build: './src/app'
    volumes:
      - './src/app:/app'
    ports:
      - '8080:80'

  docker-push:
    image: 'tmvdl/projects:counter'
    build: 
      context: './src'
      dockerfile: 'Dockerfile.nginx'

  github-release:
    image: 'github-release'
    build: 
      context: './src'
      dockerfile: 'Dockerfile.ionic'
