version: '3'

services:

  www:
    image: 'tmvdl/projects:plus'
    restart: 'always'
    build: './src/www'
    volumes:
      - './src/www:/app'
    ports:
      - '80:3000'

  app:
    image: 'app'
    build: './src'
