name: Docker pull

on:
  schedule:
    - cron: '50 * * * *'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Pull docker image
        run: docker pull tmvdl/projects -a
