name: Docker push

on:
  push:
    branches: 
      - 'main'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v1 
        with:
          username: tmvdl
          password: ${{ secrets.GITHUBDOCKER }}

      - name: Pull app 
        run: git clone git@github.com:brtmvdl/plus-www.git ./src/www

      - name: Build app 
        run: docker-compose build www

      - name: Docker push
        run: docker push tmvdl/projects:plus
