name: Docker push

on:
  push:
    branches: 
      - 'main'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v1 
        with:
          username: tmvdl
          password: ${{ secrets.GITHUBDOCKER }}

      - name: Install
        run: docker-compose run app npm i

      - name: React.js build
        run: docker-compose run app npm run build

      - name: Docker build
        run: docker-compose build docker-push

      - name: Docker push
        run: docker push tmvdl/projects -a
