name: GitHub release

on:
  schedule:
    - cron: '50 23 * * *'
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Pull project
        run: bash env/pull.sh 

      - name: Install project
        run: bash env/install.sh 

      - name: Build apk
        run: docker-compose build app

      - name: Export apk
        run: docker run -v $(pwd)/dist:/dist -w /dist apk cp /app/hello/platforms/android/app/build/outputs/apk/debug/*.apk . 

      - name: Create release
        run: gh release create v$( date +%Y%m%d%H%M ) ./dist/*.apk
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

