name: GitHub release

on:
  schedule:
    - cron: '50 23 * * *'
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Install www
        run: docker-compose run www npm i

      - name: Build www
        run: docker-compose run www npm run build

      - name: Build app
        run: docker-compose build app

      - name: Export app
        run: docker run -v $(pwd)/dist:/dist -w /dist app cp ./platforms/android/app/build/outputs/*.apk . -rfv

      - name: Create release
        run: gh release create v$( date +%Y%m%d%H%M ) ./dist/*.apk
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
